[tool.poetry]
name = "search-success-videos"
version = "0.1.2"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "search_success_videos"}]

[tool.poetry.dependencies]
python = "^3.9,<4.0"
langchain = "^0.3.3"
langchain-qdrant = "^0.1.4"
langchain-openai = "^0.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
